export const D3Classes = {
  svg: 'd3-svg',
  hintGroup: 'd3-hint-g',
  chartOverlay: 'd3-chart-overlay',
  axis: {
    bottom: 'd3-axis-bottom',
    top: 'd3-axis-top',
    left: 'd3-axis-left',
    right: 'd3-axis-right',
    group: {
      bottom: 'd3-axis-g-bottom',
      top: 'd3-axis-g-top',
      left: 'd3-axis-g-left',
      right: 'd3-axis-g-right',
    },
    tooltip: {
      x: 'd3-axis-x-tooltip',
      y: 'd3-axis-y-tooltip',
      foreignObjectX: 'd3-axis-x-f-obj',
      foreignObjectY: 'd3-axis-y-f-obj',
    },
    labels: {
      group: {
        bottom: 'd3-axis-label-bottom-g',
        top: 'd3-axis-label-top-g',
        left: 'd3-axis-label-left-g',
        right: 'd3-axis-label-right-g',
      },
      text: {
        bottom: 'd3-axis-label-bottom',
        top: 'd3-axis-label-top',
        left: 'd3-axis-label-left',
        right: 'd3-axis-label-right',
      },
    },
    ticks: {
      bottom: 'd3-axis-tick-bottom',
      top: 'd3-axis-tick-top',
      left: 'd3-axis-tick-left',
      right: 'd3-axis-tick-right',
    },
    gridLines: {
      bottom: 'd3-axis-line-v',
      top: 'd3-axis-line-v',
      left: 'd3-axis-line-h',
      right: 'd3-axis-line-h',
    },
  },
  chartElements: {
    bar: {
      allBarsGroup: 'd3-bars-g',
      bar: 'd3-bar',
      barGroup: 'd3-bar-g',
    },
    circle: {
      circle: 'd3-circle',
      circleGroup: 'd3-circle-g',
    },
    line: {
      lines: 'd3-lines-g',
      line: 'd3-line',
      lineGroup: 'd3-line-g',
      lineDot: 'd3-line-dot',
      lineDotGroup: 'd3-line-dot-g',
    },
    area: {
      areas: 'd3-areas-g',
      area: 'd3-area',
      areaGroup: 'd3-area-g',
      areaDot: 'd3-area-dot',
      areaDotGroup: 'd3-area-dot-g',
    },
    density: {
      densities: 'd3-densities-g',
      density: 'd3-density',
      densityGroup: 'd3-density-g',
      densityDot: 'd3-density-dot',
      densityDotGroup: 'd3-density-dot-g',
    },
    violin: {
      violin: 'd3-violin',
      allViolinsGroup: 'd3-violins-g',
      violinGroup: 'd3-violin-g',
    },
    title: {
      title: 'd3-chart-title',
      group: 'd3-chart-title-g',
    },
    brush: {
      overlay: 'd3-brush-overlay',
      selection: 'd3-brush-selection',
      rect: 'd3-brush-rect',
      handleL: 'd3-brush-handle-l',
      handleR: 'd3-brush-handle-r',
      group: 'd3-brush-g',
    },
    vLine: {
      group: 'd3-vline-g',
      line: 'd3-vline',
    },
  },
  events: {
    hovered: 'd3-hover',
    mouseVerticalLine: 'd3-mouse-v-line',
    mouseHorizontalLine: 'd3-mouse-h-line',
    mouseRect: 'd3-mouse-rect',
    mouseEventsGroup: 'd3-mouse-g',
    crossHairVertical: 'd3-crosshair-v',
    crossHairHorizontal: 'd3-crosshair-h',
  },
  tooltip: 'd3-tooltip',
};
